---
version: 2
run:
  timeout: 5m
  tests: true
  go: "1.25"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - misspell
    - revive
    - gosec

issues:
  exclude-use-default: false
