version: 2
project_name: skv
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: skv
    main: ./cmd/skv
    binary: skv
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X skv/internal/version.Version={{.Version}}
      - -X skv/internal/version.Commit={{.ShortCommit}}
      - -X skv/internal/version.Date={{.Date}}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - id: binary
    builds: [skv]
    format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  - id: archive
    builds: [skv]
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - completions/*
checksum:
  name_template: "checksums.txt"
release:
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## {{ .ProjectName }} {{ .Tag }}

    ### Installation

    Download the appropriate binary for your platform below.

    #### Linux/macOS
    ```bash
    # Download and install
    curl -sL "https://github.com/Amet13/skv/releases/download/{{ .Tag }}/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}" -o skv
    chmod +x skv
    sudo mv skv /usr/local/bin/

    # Verify installation
    skv version
    ```

    #### Homebrew (macOS/Linux)
    ```bash
    # Coming soon
    brew install amet13/tap/skv
    ```
  footer: |
    **Full Changelog**: https://github.com/Amet13/skv/compare/{{ .PreviousTag }}...{{ .Tag }}
  extra_files:
    - glob: completions/*
changelog:
  use: github
  sort: asc
  abbrev: 7
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Security Updates"
      regexp: "^.*sec[(\\w)]*:+.*$"
      order: 2
    - title: "Documentation Updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 3
    - title: "Other Changes"
      order: 999
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
sboms:
  - artifacts: archive
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
nfpms:
  - id: packages
    builds: [skv]
    package_name: skv
    vendor: skv contributors
    homepage: https://github.com/Amet13/skv
    maintainer: skv contributors
    description: CLI tool that fetches secrets from different providers
    license: MIT
    formats: [deb, rpm, apk]
    dependencies: []
    recommends: []
    suggests: []
    conflicts: []
    replaces: []
    contents:
      - src: completions/skv.bash
        dst: /usr/share/bash-completion/completions/skv
        file_info:
          mode: 0644
      - src: completions/_skv
        dst: /usr/share/zsh/site-functions/_skv
        file_info:
          mode: 0644
      - src: completions/skv.fish
        dst: /usr/share/fish/vendor_completions.d/skv.fish
        file_info:
          mode: 0644
brews:
  - name: skv
    repository:
      owner: Amet13
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/Amet13/skv
    description: CLI tool that fetches secrets from different providers
    license: MIT
    test: |
      system "#{bin}/skv version"
    install: |
      bin.install "skv"
      bash_completion.install "completions/skv.bash" => "skv"
      zsh_completion.install "completions/_skv"
      fish_completion.install "completions/skv.fish"
scoop:
  bucket:
    owner: Amet13
    name: scoop-bucket
    token: "{{ .Env.SCOOP_GITHUB_TOKEN }}"
  homepage: https://github.com/Amet13/skv
  description: CLI tool that fetches secrets from different providers
  license: MIT
announce:
  skip: "{{gt .Patch 0}}"
