---
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: skv
    main: ./cmd/skv
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X skv/internal/version.Version={{.Version}}
      - -X skv/internal/version.Commit={{.ShortCommit}}
      - -X skv/internal/version.Date={{.Date}}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
archives:
  disable: true
checksum:
  name_template: "checksums.txt"
sboms:
  disable: true
changelog:
  use: github
release:
  draft: false
  prerelease: auto
