extends: default
rules:
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]
  indentation:
    spaces: 2
    indent-sequences: consistent
ignore:
  - .markdownlint.yaml
