---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
          cache: true
      - name: Build
        run: ./build.sh host
      - name: Lint and test with coverage (threshold)
        run: |
          go test ./... -coverprofile=coverage.out -covermode=atomic
          go tool cover -func=coverage.out | awk -v threshold=60.0 '
            /total:/ {
              gsub("%","",$3)
              if ($3+0 < threshold) {
                printf "Coverage %.2f%% below %.2f%%\n", $3, threshold
                exit 1
              }
            }
          '

          ./scripts/lint.sh
