---
name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: ["**"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
          cache: true
      - name: Build
        run: bash ./build.sh host
      - name: Lint and test with coverage (threshold)
        run: |
          go test ./... -coverprofile=coverage.out -covermode=atomic
          go tool cover -func=coverage.out | awk -v threshold=80.0 '
            /total:/ {
              gsub("%","",$3)
              if ($3+0 < threshold) {
                printf "Coverage %.2f%% below %.2f%%\n", $3, threshold
                exit 1
              }
            }
          '
          bash ./scripts/lint.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.out
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: skv-dist
          path: dist/
